-- ═══════════════════════════════════════════════════════════════
-- Migration: 045_seed_rubrics.sql
-- Description: Seed grading rubrics for SQL and Excel courses.
-- ═══════════════════════════════════════════════════════════════

INSERT INTO public.grading_rubrics (day_id, cell_id, question_text, kernel, marks, ignore_tokens)
VALUES
('sql-day01', 'cell-2', '**Q1.** Write a query to retrieve all columns from the `products` table.', 'sql', 10, '{}'),
('sql-day01', 'cell-3', '**Q2.** Retrieve only the `name` and `unit_price` columns from the `products` table.', 'sql', 10, '{}'),
('sql-day01', 'cell-4', '**Q3.** Retrieve the `product` and `amount` from the `sales` table, aliasing `product` as `product_name` and `amount` as `sale_value`.', 'sql', 10, '{}'),
('sql-day01', 'cell-5', '**Q4.** List all unique (distinct) product categories from the `sales` table.', 'sql', 10, '{}'),
('sql-day01', 'cell-6', '**Q5.** Write a query to find all unique regions from the `sales` table.', 'sql', 10, '{}'),
('sql-day01', 'cell-7', '**Task 1 (Categories Sold):** Write a query to list all unique product categories sold from the `sales` table.', 'sql', 10, '{}'),
('sql-day02', 'cell-2', '**Q1.** Find all sales where the `category` is ''Electronics''.', 'sql', 10, '{}'),
('sql-day02', 'cell-3', '**Q2.** Find all sales where the `amount` is between 5000 and 10000 (inclusive) using `BETWEEN`.', 'sql', 10, '{}'),
('sql-day02', 'cell-4', '**Q3.** Get all products in the `products` table where `unit_price` is less than or equal to 2000.', 'sql', 10, '{}'),
('sql-day02', 'cell-5', '**Q4.** Find sales in ''South'' or ''West'' regions using the `IN` operator.', 'sql', 10, '{}'),
('sql-day02', 'cell-6', '**Q5.** Find sales that are NOT in the ''North'' region.', 'sql', 10, '{}'),
('sql-day02', 'cell-7', '**Task 1 (High Value North):** Find all sales over ₹5,000 in the ''North'' region.', 'sql', 10, '{}'),
('sql-day03', 'cell-2', '**Q1.** Find all sales records where `customer_name` starts with the letter ''A''.', 'sql', 10, '{}'),
('sql-day03', 'cell-3', '**Q2.** Find all sales records where `customer_email` is NULL.', 'sql', 10, '{}'),
('sql-day03', 'cell-4', '**Q3.** Find all sales records where `customer_email` is NOT NULL.', 'sql', 10, '{}'),
('sql-day03', 'cell-5', '**Q4.** Write a query using `COALESCE` to display the customer''s email, or the text ''No Email'' if it is NULL.', 'sql', 10, '{}'),
('sql-day03', 'cell-6', '**Q5.** Find sales where the product name ends with ''Book''.', 'sql', 10, '{}'),
('sql-day03', 'cell-7', '**Task 1 (Customer Search):** Find all customers whose names start with ''A'' or have a NULL email.', 'sql', 10, '{}'),
('sql-day04', 'cell-2', '**Q1.** Sort the `sales` table by `amount` in descending order.', 'sql', 10, '{}'),
('sql-day04', 'cell-3', '**Q2.** Sort the `sales` table by `region` ascending, and then by `amount` descending.', 'sql', 10, '{}'),
('sql-day04', 'cell-4', '**Q3.** Get the top 5 highest sales amount records.', 'sql', 10, '{}'),
('sql-day04', 'cell-5', '**Q4.** Get the 5 next highest sales amount records (skipping the top 5) using `OFFSET`.', 'sql', 10, '{}'),
('sql-day04', 'cell-6', '**Q5.** Sort the `products` table by `stock_qty` ascending, placing any NULL stock values last.', 'sql', 10, '{}'),
('sql-day04', 'cell-7', '**Task 1 (Top Sales):** Get the top 10 highest-value sales, most recent first.', 'sql', 10, '{}'),
('sql-day05', 'cell-2', '**Q1.** Count the total number of products in the `products` table.', 'sql', 10, '{}'),
('sql-day05', 'cell-3', '**Q2.** Find the total stock quantity of all products combined.', 'sql', 10, '{}'),
('sql-day05', 'cell-4', '**Q3.** Find the average price of products in the ''Electronics'' category.', 'sql', 10, '{}'),
('sql-day05', 'cell-5', '**Q4.** Find the lowest and highest unit prices in the `products` table.', 'sql', 10, '{}'),
('sql-day05', 'cell-6', '**Q5.** Count the number of sales that occurred in the ''North'' region.', 'sql', 10, '{}'),
('sql-day05', 'cell-7', '**Task 1 (Category Average):** Calculate the average sale value in the ''Books'' category.', 'sql', 10, '{}'),
('sql-day06', 'cell-2', '**Q1.** Group `sales` by `category` and find the total count of sales for each.', 'sql', 10, '{}'),
('sql-day06', 'cell-3', '**Q2.** Group `sales` by `region` and find the average sale amount per region.', 'sql', 10, '{}'),
('sql-day06', 'cell-4', '**Q3.** Find product categories with total sales revenue greater than 50,000.', 'sql', 10, '{}'),
('sql-day06', 'cell-5', '**Q4.** Find the number of orders placed by each customer_id.', 'sql', 10, '{}'),
('sql-day06', 'cell-6', '**Q5.** Show regions that have more than 20 sales transactions.', 'sql', 10, '{}'),
('sql-day06', 'cell-7', '**Task 1 (High Value Groups):** Find categories with more than 30 orders and average sale > ₹3,000.', 'sql', 10, '{}'),
('sql-day07', 'cell-2', '**Q1.** Calculate a 10% VAT tax for each product in the `products` table (unit_price * 0.10).', 'sql', 10, '{}'),
('sql-day07', 'cell-3', '**Q2.** Retrieve product names and calculate their total value in stock (`unit_price * stock_qty`).', 'sql', 10, '{}'),
('sql-day07', 'cell-4', '**Q3.** Explicitly cast the `amount` column in the `sales` table as an INTEGER.', 'sql', 10, '{}'),
('sql-day07', 'cell-5', '**Q4.** Concatenate product `name` and `category` from the `products` table separated by a hyphen.', 'sql', 10, '{}'),
('sql-day07', 'cell-6', '**Q5.** Write a query to find the modulus (remainder) of `stock_qty` divided by 10 for all products.', 'sql', 10, '{}'),
('sql-day07', 'cell-7', '**Task 1 (Revenue Tier):** Calculate a custom ''projected_price'' for each product if it rises by 15%.', 'sql', 10, '{}'),
('sql-day08', 'cell-2', '**Q1.** Classify sales amounts as ''Small'' (under 2000), ''Medium'' (2000 to 8000), and ''Large'' (above 8000).', 'sql', 10, '{}'),
('sql-day08', 'cell-3', '**Q2.** Write a query displaying product name, stock quantity, and status: ''Out of Stock'' (stock_qty = 0), ''Low Stock'' (under 20), ''In Stock'' (otherwise).', 'sql', 10, '{}'),
('sql-day08', 'cell-4', '**Q3.** Use a CASE statement inside `SUM` to count how many sales occurred in the ''North'' region.', 'sql', 10, '{}'),
('sql-day08', 'cell-5', '**Q4.** Pivot sales: write a query displaying total amount for ''Electronics'' and total amount for ''Books'' as two separate columns.', 'sql', 10, '{}'),
('sql-day08', 'cell-6', '**Q5.** Classify regions: if region is ''North'' or ''East'' then ''Group A'', else ''Group B''.', 'sql', 10, '{}'),
('sql-day08', 'cell-7', '**Task 1 (Tier Counts):** Classify each sale as ''Low'', ''Medium'', ''High'' value; count the number of sales in each tier.', 'sql', 10, '{}'),
('sql-day09', 'cell-2', '**Q1.** Join `employees` and `departments` to list employee names, department names, and department budgets.', 'sql', 10, '{}'),
('sql-day09', 'cell-3', '**Q2.** Join `employees` and `salaries` to find the current salary amount for each employee (effective_date = hire_date or matching dates).', 'sql', 10, '{}'),
('sql-day09', 'cell-4', '**Q3.** Retrieve employee name, project name, and role for all assigned projects by joining `employees`, `emp_projects`, and `projects`.', 'sql', 10, '{}'),
('sql-day09', 'cell-5', '**Q4.** Find the names of employees in the ''Engineering'' department.', 'sql', 10, '{}'),
('sql-day09', 'cell-6', '**Q5.** Write a query displaying employee name and their current salary, filtering for salaries above 80000.', 'sql', 10, '{}'),
('sql-day09', 'cell-7', '**Task 1 (Department Salaries):** Get each employee''s name with their department name and salary.', 'sql', 10, '{}'),
('sql-day10', 'cell-2', '**Q1.** Write a query using a `LEFT JOIN` to list all departments and their employee count.', 'sql', 10, '{}'),
('sql-day10', 'cell-3', '**Q2.** Find all employees who are NOT assigned to any project by LEFT joining `employees` to `emp_projects`.', 'sql', 10, '{}'),
('sql-day10', 'cell-4', '**Q3.** List all projects and any employee names assigned to them, including projects with no employees.', 'sql', 10, '{}'),
('sql-day10', 'cell-5', '**Q4.** Use a LEFT JOIN and a WHERE condition to list departments that have NO employees assigned.', 'sql', 10, '{}'),
('sql-day10', 'cell-6', '**Q5.** Display employees and their salaries using a LEFT JOIN, showing NULL for any employee without a salary record.', 'sql', 10, '{}'),
('sql-day10', 'cell-7', '**Task 1 (Empty Departments):** Find all departments that have NO employees assigned.', 'sql', 10, '{}'),
('sql-day11', 'cell-2', '**Q1.** Write a query to find all employees managed by ''Rajesh Sen''.', 'sql', 10, '{}'),
('sql-day11', 'cell-3', '**Q2.** Find employees who do NOT have any manager (top of the hierarchy).', 'sql', 10, '{}'),
('sql-day11', 'cell-4', '**Q3.** Write a SELF JOIN to find pairs of employees who work in the same department (excluding pairing an employee with themselves).', 'sql', 10, '{}'),
('sql-day11', 'cell-5', '**Q4.** Find employees whose manager works in a different department (dept_id differs).', 'sql', 10, '{}'),
('sql-day11', 'cell-6', '**Q5.** Find the names of managers who manage more than 2 employees.', 'sql', 10, '{}'),
('sql-day11', 'cell-7', '**Task 1 (Manager Names):** List every employee with their manager''s name.', 'sql', 10, '{}'),
('sql-day12', 'cell-2', '**Q1.** Find customers who signed up after ''Sneha Patel'' signed up.', 'sql', 10, '{}'),
('sql-day12', 'cell-3', '**Q2.** Find products in the `products` table that have never been ordered using `NOT IN` or `NOT EXISTS`.', 'sql', 10, '{}'),
('sql-day12', 'cell-4', '**Q3.** Get the names of customers who have placed at least one order.', 'sql', 10, '{}'),
('sql-day12', 'cell-5', '**Q4.** Get the maximum order quantity of any product in a single order item.', 'sql', 10, '{}'),
('sql-day12', 'cell-6', '**Q5.** Find all order IDs that contain the product ''MacBook Pro''.', 'sql', 10, '{}'),
('sql-day12', 'cell-7', '**Task 1 (Above Average Spend):** Find customers who ordered more than the average order value.', 'sql', 10, '{}'),
('sql-day13', 'cell-2', '**Q1.** Write a CTE named `CustomerOrders` that counts orders per customer, then select all columns from it.', 'sql', 10, '{}'),
('sql-day13', 'cell-3', '**Q2.** Use a CTE to calculate the average price of products ordered in each category, then join it to `categories`.', 'sql', 10, '{}'),
('sql-day13', 'cell-4', '**Q3.** Write a query with two chained CTEs: one calculating product costs, and the second ranking them.', 'sql', 10, '{}'),
('sql-day13', 'cell-5', '**Q4.** Rewrite a subquery that retrieves products costing more than average cost using a CTE instead.', 'sql', 10, '{}'),
('sql-day13', 'cell-6', '**Q5.** Use a CTE to find customers with more than 2 orders.', 'sql', 10, '{}'),
('sql-day13', 'cell-7', '**Task 1 (Category Ranks):** Use a CTE to calculate total revenue for each product, then join with products to display product name and revenue.', 'sql', 10, '{}'),
('sql-day14', 'cell-2', '**Q1.** Assign a sequential row number to all customers ordered by their `signup_date`.', 'sql', 10, '{}'),
('sql-day14', 'cell-3', '**Q2.** Rank products globally by `cost_price` descending using `RANK()` and `DENSE_RANK()`.', 'sql', 10, '{}'),
('sql-day14', 'cell-4', '**Q3.** Partition customers by `region` and rank them by `signup_date` ascending.', 'sql', 10, '{}'),
('sql-day14', 'cell-5', '**Q4.** Write a query using `NTILE(4)` to divide products into 4 price quartiles.', 'sql', 10, '{}'),
('sql-day14', 'cell-6', '**Q5.** Use `ROW_NUMBER()` inside a subquery or CTE to find the oldest customer in each region.', 'sql', 10, '{}'),
('sql-day14', 'cell-7', '**Task 1 (Spend Rankings):** Rank customers by total order spend within each region.', 'sql', 10, '{}'),
('sql-day15', 'cell-2', '**Q1.** Use `LAG()` to show the signup date of the previous customer registered on the system.', 'sql', 10, '{}'),
('sql-day15', 'cell-3', '**Q2.** Use `LEAD()` to show the signup date of the next customer registered on the system.', 'sql', 10, '{}'),
('sql-day15', 'cell-4', '**Q3.** Calculate a running sum of order revenue grouped by customer, ordered by order date.', 'sql', 10, '{}'),
('sql-day15', 'cell-5', '**Q4.** Use `FIRST_VALUE()` to display the first product ordered by each customer.', 'sql', 10, '{}'),
('sql-day15', 'cell-6', '**Q5.** Calculate a 3-period moving average of product costs using `ROWS BETWEEN 2 PRECEDING AND CURRENT ROW`.', 'sql', 10, '{}'),
('sql-day15', 'cell-7', '**Task 1 (Growth Analysis):** Calculate the difference in cost price between each product and the next most expensive product using LEAD.', 'sql', 10, '{}'),
('sql-day16', 'cell-2', '**Q1.** Convert customer names to uppercase and emails to lowercase.', 'sql', 10, '{}'),
('sql-day16', 'cell-3', '**Q2.** Trim extra spaces from customer names and replace the domain ''@gmail.com'' with ''@googlemail.com''.', 'sql', 10, '{}'),
('sql-day16', 'cell-4', '**Q3.** Extract the first 3 characters of each customer''s region using `SUBSTR`.', 'sql', 10, '{}'),
('sql-day16', 'cell-5', '**Q4.** Find the character position of ''@'' in each customer''s email using `INSTR`.', 'sql', 10, '{}'),
('sql-day16', 'cell-6', '**Q5.** Find the length (number of characters) of customer emails.', 'sql', 10, '{}'),
('sql-day16', 'cell-7', '**Task 1 (Standardize Names):** Standardize the customer names column to remove spaces and convert to uppercase.', 'sql', 10, '{}'),
('sql-day17', 'cell-2', '**Q1.** Find all orders placed in the year 2022.', 'sql', 10, '{}'),
('sql-day17', 'cell-3', '**Q2.** Find all orders placed in the month of October.', 'sql', 10, '{}'),
('sql-day17', 'cell-4', '**Q3.** Find orders placed on weekends (STRFTIME ''%w'' is ''0'' or ''6'').', 'sql', 10, '{}'),
('sql-day17', 'cell-5', '**Q4.** Calculate the number of days between customer signup date and their first order date.', 'sql', 10, '{}'),
('sql-day17', 'cell-6', '**Q5.** List all customers who signed up in Q4 of 2022 (Oct, Nov, Dec).', 'sql', 10, '{}'),
('sql-day17', 'cell-7', '**Task 1 (Q4 Weekends):** Find all orders placed on weekends in Q4 of 2022.', 'sql', 10, '{}'),
('sql-day18', 'cell-2', '**Q1.** Get a unique list of all customer names and employee names (cross-database conceptually, but here combine customer names and product names for syntax practice).', 'sql', 10, '{}'),
('sql-day18', 'cell-3', '**Q2.** Find customer IDs who ordered both in October and in December using `INTERSECT`.', 'sql', 10, '{}'),
('sql-day18', 'cell-4', '**Q3.** List all customers who registered on the system but have placed NO orders using `EXCEPT`.', 'sql', 10, '{}'),
('sql-day18', 'cell-5', '**Q4.** Combine order items with product cost price and sale price, maintaining duplicates via `UNION ALL`.', 'sql', 10, '{}'),
('sql-day18', 'cell-6', '**Q5.** Find customer IDs who ordered in 2022 but did not order in 2023.', 'sql', 10, '{}'),
('sql-day18', 'cell-7', '**Task 1 (Customer Activity Sets):** Find customer IDs who signed up in 2022 and ordered in 2022.', 'sql', 10, '{}'),
('sql-day19', 'cell-2', '**Q1.** Run an `EXPLAIN QUERY PLAN` on a query that joins `orders` and `customers`.', 'sql', 10, '{}'),
('sql-day19', 'cell-3', '**Q2.** Run `EXPLAIN QUERY PLAN` on a query searching customer names by a LIKE pattern (`customer_name LIKE ''%Sharma%'')`.', 'sql', 10, '{}'),
('sql-day19', 'cell-4', '**Q3.** Rewrite a query containing `SELECT *` to retrieve only required columns.', 'sql', 10, '{}'),
('sql-day19', 'cell-5', '**Q4.** Explain what indexing does and when it can slow down operations.', 'sql', 10, '{}'),
('sql-day19', 'cell-6', '**Q5.** Identify why filtering on a function (e.g. `WHERE UPPER(name) = ''AMIT''`) might bypass standard indexes.', 'sql', 10, '{}'),
('sql-day19', 'cell-7', '**Task 1 (Read Plans):** Run EXPLAIN QUERY PLAN on a query that calculates the total spend per customer.', 'sql', 10, '{}'),
('sql-day20', 'cell-2', '**Q1. Monthly Trend:** Calculate total revenue and order count by month (using `sale_date`).', 'sql', 10, '{}'),
('sql-day20', 'cell-3', '**Q2. Top Products:** Find the top 10 products by revenue, displaying product name and category.', 'sql', 10, '{}'),
('sql-day20', 'cell-4', '**Q3. Repeat Buyers:** Count customer segmentation: how many customers placed 1 order vs repeat buyers (2+ orders)?', 'sql', 10, '{}'),
('sql-day20', 'cell-5', '**Q4. Regional Performance:** List revenue, average order value, and count of sales reps in each region.', 'sql', 10, '{}'),
('sql-day20', 'cell-6', '**Q5. Return Rates:** Calculate the return rate (orders returned / total orders) for each product category.', 'sql', 10, '{}'),
('sql-day20', 'cell-7', '**Q6. Sales Rep Ranks:** Rank sales reps by revenue generated within their assigned region using window functions.', 'sql', 10, '{}'),
('sql-day20', 'cell-8', '**Q7. Cohort Analysis:** Group customers by signup month and find their Lifetime Value (LTV).', 'sql', 10, '{}'),
('sql-day20', 'cell-9', '**Q8. Day-of-Week:** Find which day of the week (Sunday-Saturday) generates the highest average sale amount.', 'sql', 10, '{}'),
('sql-day20', 'cell-10', '**Task 1 (Final Query):** Write a query to retrieve the overall return percentage of the retail business.', 'sql', 10, '{}'),
('excel-day01', 'cell-2', '**Q1.** Calculate the product of A2 and B2.', 'excel', 10, '{}'),
('excel-day01', 'cell-3', '**Q2.** Sum the quantities in cells A1, A2, and A3 using basic addition (+).', 'excel', 10, '{}'),
('excel-day01', 'cell-4', '**Q3.** Subtract tax C1 from price B1.', 'excel', 10, '{}'),
('excel-day01', 'cell-5', '**Q4.** Divide price B2 by quantity A2.', 'excel', 10, '{}'),
('excel-day01', 'cell-6', '**Q5.** Calculate total price including tax for item 3 (A3 * B3 + C3).', 'excel', 10, '{}'),
('excel-day01', 'cell-7', '**Task 1 (Aggregate Quantity):** Calculate the sum of all quantities from A1 to A3 using the SUM function.', 'excel', 10, '{}'),
('excel-day02', 'cell-2', '**Q1.** Find the total price of all items in column C.', 'excel', 10, '{}'),
('excel-day02', 'cell-3', '**Q2.** Find the average rating of items in column B.', 'excel', 10, '{}'),
('excel-day02', 'cell-4', '**Q3.** Count the number of items listed in column A using the COUNT function on ratings in column B.', 'excel', 10, '{}'),
('excel-day02', 'cell-5', '**Task 1 (Total Rating):** Calculate the sum of all ratings from B1 to B3.', 'excel', 10, '{}'),
('excel-day03', 'cell-2', '**Q1.** Convert text in A2 to lowercase.', 'excel', 10, '{}'),
('excel-day03', 'cell-3', '**Q2.** Convert text in A1 to uppercase.', 'excel', 10, '{}'),
('excel-day03', 'cell-4', '**Q3.** Find the total values in B1 and B2.', 'excel', 10, '{}'),
('excel-day03', 'cell-5', '**Task 1 (Total Values):** Calculate the sum of all numerical cell values from B1 to B2.', 'excel', 10, '{}'),
('excel-day04', 'cell-2', '**Q1.** Calculate sum of A1 and B1.', 'excel', 10, '{}'),
('excel-day04', 'cell-3', '**Q2.** Calculate sum of A2 and B2.', 'excel', 10, '{}'),
('excel-day04', 'cell-4', '**Q3.** Calculate total base in range A1:A2.', 'excel', 10, '{}'),
('excel-day04', 'cell-5', '**Task 1 (Total Earnings):** Calculate total base plus bonus in range A1:B2.', 'excel', 10, '{}'),
('excel-day05', 'cell-2', '**Q1.** Convert B2 item name to uppercase.', 'excel', 10, '{}'),
('excel-day05', 'cell-3', '**Q2.** Convert B1 item name to lowercase.', 'excel', 10, '{}'),
('excel-day05', 'cell-4', '**Q3.** Find sum of A1 and A2.', 'excel', 10, '{}'),
('excel-day05', 'cell-5', '**Task 1 (ID Casing):** Convert item name Tablet in B1 to uppercase.', 'excel', 10, '{}'),
('excel-day06', 'cell-2', '**Q1.** Check if student 1 grade A1 is >= 50. Return 1 if true, else 0.', 'excel', 10, '{}'),
('excel-day06', 'cell-3', '**Q2.** Check if student 2 grade A2 is >= 50. Return 1 if true, else 0.', 'excel', 10, '{}'),
('excel-day06', 'cell-4', '**Q3.** Check if student 1 attendance B1 is >= 75. Return 1 if true, else 0.', 'excel', 10, '{}'),
('excel-day06', 'cell-5', '**Task 1 (Pass Check):** Check if student 2 grade in A2 is >= 50, returning 1 if true and 0 if false.', 'excel', 10, '{}'),
('excel-day07', 'cell-2', '**Q1.** Join first and last name in row 2 using CONCAT.', 'excel', 10, '{}'),
('excel-day07', 'cell-3', '**Q2.** Convert first name in A1 to uppercase.', 'excel', 10, '{}'),
('excel-day07', 'cell-4', '**Q3.** Convert last name in B2 to lowercase.', 'excel', 10, '{}'),
('excel-day07', 'cell-5', '**Task 1 (Full Name):** Join Rahul and Sharma in row 1 using CONCAT.', 'excel', 10, '{}'),
('excel-day08', 'cell-2', '**Q1.** Calculate difference between B2 and A2.', 'excel', 10, '{}'),
('excel-day08', 'cell-3', '**Q2.** Find sum of start days A1 and A2.', 'excel', 10, '{}'),
('excel-day08', 'cell-4', '**Q3.** Find average of end days B1 and B2.', 'excel', 10, '{}'),
('excel-day08', 'cell-5', '**Task 1 (Date Difference):** Calculate B2 minus A2.', 'excel', 10, '{}'),
('excel-day09', 'cell-2', '**Q1.** Find the sum of all amounts in range A1:A3.', 'excel', 10, '{}'),
('excel-day09', 'cell-3', '**Q2.** Check if row 2 status B2 is Pending, returning A2 if true and 0 if false.', 'excel', 10, '{}'),
('excel-day09', 'cell-4', '**Q3.** Convert status B1 to uppercase.', 'excel', 10, '{}'),
('excel-day09', 'cell-5', '**Task 1 (Paid Amount Check):** Check if status B3 is Paid, returning amount A3 if true and 0 if false.', 'excel', 10, '{}'),
('excel-day10', 'cell-2', '**Q1.** Sum values in B1 and B2.', 'excel', 10, '{}'),
('excel-day10', 'cell-3', '**Q2.** Find the average of values in range B1:B2.', 'excel', 10, '{}'),
('excel-day10', 'cell-4', '**Q3.** Convert category in A1 to lowercase.', 'excel', 10, '{}'),
('excel-day10', 'cell-5', '**Task 1 (Total revenue):** Calculate sum of all revenues from B1 to B2.', 'excel', 10, '{}'),
('excel-day11', 'cell-2', '**Q1.** Calculate average hours worked across B1:B2.', 'excel', 10, '{}'),
('excel-day11', 'cell-3', '**Q2.** Check if project in A1 is Alpha, returning B1 if true and 0 if false.', 'excel', 10, '{}'),
('excel-day11', 'cell-4', '**Q3.** Join A1 and A2 using CONCAT.', 'excel', 10, '{}'),
('excel-day11', 'cell-5', '**Task 1 (Total Hours):** Calculate the sum of all hours from B1 to B2.', 'excel', 10, '{}'),
('excel-day12', 'cell-2', '**Q1.** Calculate profit for project 2 (B2 - A2).', 'excel', 10, '{}'),
('excel-day12', 'cell-3', '**Q2.** Calculate total cost across A1:A2.', 'excel', 10, '{}'),
('excel-day12', 'cell-4', '**Q3.** Calculate total revenue across B1:B2.', 'excel', 10, '{}'),
('excel-day12', 'cell-5', '**Task 1 (Total Profit):** Calculate total profit across both projects (B1 - A1 + B2 - A2).', 'excel', 10, '{}')
ON CONFLICT (day_id, cell_id) DO UPDATE SET question_text = EXCLUDED.question_text, kernel = EXCLUDED.kernel;
